language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"

install: 
  - wget https://github.com/teragonaudio/MrsWatson/zipball/master
  - unzip tmp/MrsWatson-master.zip
  - cd MrsWatson-master && ./configure --prefix=/usr && make && make install