language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"

install: 
  - wget https://github.com/teragonaudio/MrsWatson/zipball/master
  - unzip teragonaudio-MrsWatson-0.9.7-15-g440b112.zip
  - cd teragonaudio-MrsWatson-0.9.7-15-440b112 && ./configure --prefix=/usr && make && make install